image: golang:1.22

variables:
  REPO_NAME: github.com/fabian/slog-loki
  GOPATH: $CI_PROJECT_DIR/go

before_script:
  - export PATH=$(go env GOPATH)/bin:$PATH
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - go/pkg/mod/

stages:
  - build
  - test

compile:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go get github.com/boumenot/gocover-cobertura
    - go test -cover -covermode count -coverprofile=coverage.txt ./...
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 30d
